replicaCount: 1

image:
  repository: mdhack016/myapache
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  
color:
   circle: black
   oval: black
   triangle: black
   rectangle: black
   square: black    
